pring.sleuth.sampler.probability: 1.0
server.port: 8761
spring:
  application:
    name: eurekaApp

eureka:
  server:
    enable-self-preservation: false
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
#    eureka server를 클라이언트로 등록
    register-with-eureka: false
#    client에서 서비스 리스트를 캐싱
    fetch-registry: false
    service-url:
      default-zone: http://${eureka.instance.hostname}:${server.port}/eureka/
